### ISSUE TITLE
Box won't embed sometimes. + solution

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Controlfreak707/undertale-dialog-generator#2]
Boxes won't embed occaisionally, and it's mostly because of how parameters work in the URL.
When the box is generated while a couple parameters aren't set in the plugin settings it shouldn't leave the parameters in the URL as it can cause issues when attempting to generate/embed. The parameter should be removed completely from the URL when generating.

*this box is an example given by a friend.

https://www.demirramon.com/utgen.png?text=jajaja&box=undertale&boxcolor=white&character=custom&expression=default&url=https%3A%2F%2Fcdn.discordapp.com%2Favatars%2F347480326077022237%2Fe756f604d7c0c38ec16375f644ee33e4.png%3Fsize%3D128&mode=

Parameters like, mode=, box=, color= and expression= shouldn't be in the URL unless specified to be different, otherwise issues like this one occur.

**Comment by Controlfreak707** [comment]
Oh, thank you! I've known abot this issue but I've kinda stopped working on the plugin... I'll update it in a minute!

**Comment by Mr-Foxtrot** [comment]
Thanks!

**Comment by Mr-Foxtrot** [comment]
"box=undertale&expression=default" still show up in the URL even when the expression or box isn't changed (it shouldn't be in the URL if those parameters are already set to default)

**Comment by Mr-Foxtrot** [comment]
Another solution I thought of to completely get rid of any possible embed problems is to just upload the url as an attachment rather than a URL that needs to embed. Not sure if that would be allowed though.

**Comment by Controlfreak707** [comment]
> Another solution I thought of to completely get rid of any possible embed problems is to just upload the url as an attachment rather than a URL that needs to embed. Not sure if that would be allowed though.

I've tried before to no avail, but I can always try again sometime. I'll definitely get rid of default values once I get on my computer later today.

**Comment by Mr-Foxtrot** [comment]
Alrighty!
