### ISSUE TITLE
[Suggestion] Toggle Button

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Controlfreak707/undertale-dialog-generator#3]
Toggle UT gen Button:
Right clicking the generator button will act as a toggle, so all messages you type willl send as boxes when enabled.
To let the user know if it's toggled on or not, the heart could be made to be in color.

I suggest this, since having to type out the command, using the menu, or copy + paste it every time you wish to send a box can be tedious. So an option to just toggle it on and off would be neat.

A way to see the box in a small preview to the right of the text channel while typing would be handy too, say when it's being used as a command or as a toggle option mentioned above. It would be handy, since the text box can't support huge sentences/words or else the text gets cut off.

**Comment by Controlfreak707** [comment]
I think this is a very neat idea, however, I can't guarantee it'll be a feature. This sounds like it'd be a bit difficult (for me at least)... Once I have the time I will look into this further. Thank you for your contribution!

**Comment by Controlfreak707** [comment]
Good news! Literally just a day after, I did it! You can now update and enjoy. (I had to change it just a tad. Instead of right clicking, you hold Alt and click and instead of seeing a preview, which would've been very difficult to make, you get a warning when you pass the character limit.)

**Comment by Mr-Foxtrot** [comment]
Sweet! Thanks!
